# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Build stuff
        run: |
          npm i
          npm run build
      - name: Move buit package
        run: cp dist/dc-aplayer.js public/dc-aplayer.js
      - name: Reference the new built package in the demo html
        run: sed -i 's/\/src\/dc-aplayer\.ts/\.\/public\/dc-aplayer\.js/g' index.html 
      - name: Initialize mandatory git config
        run: |
         git config user.name "GitHub Actions"
         git config user.email noreply@github.com
      - name: Checkout to tmp branch
        run: git checkout -b demo
      - name: Update demo
        run: |
          git add index.html public/dc-aplayer.js
          git commit -m"update demo"
      - name: Push to demo branch
        run: git push origin demo -f
